const sampleListings = [
  {
    title: "Cozy Beachfront Villa in Goa",
    description: "Escape to this private oceanfront sanctuary with direct beach access, panoramic Arabian Sea views, infinity plunge pool, and tropical coconut groves.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    price: 9500,
    location: "Anjuna, Goa",
    country: "India",
    category: "beach",
  },
  {
    title: "Modern Glass Treehouse in Bali",
    description: "Suspended amidst lush Ubud jungle foliage, enjoy open-air living, sunrise views over rice terraces, outdoor rain shower, and pure tranquil relaxation.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
    price: 14200,
    location: "Ubud, Bali",
    country: "Indonesia",
    category: "trending",
  },
  {
    title: "Alpine Chalet with Mont Blanc Views",
    description: "Charming traditional cedar chalet located in the French Alps. Warm stone fireplace, private sauna, heated ski room, and ski-in/ski-out convenience.",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=1200&q=80",
    price: 22000,
    location: "Chamonix",
    country: "France",
    category: "mountains",
  },
  {
    title: "Santorini Sunset Cliffside Cave Suite",
    description: "Whitewashed Cycladic architecture perched high on the Caldera cliffs. Unobstructed world-famous sunset vistas with private heated jacuzzi tub.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    price: 31000,
    location: "Oia, Santorini",
    country: "Greece",
    category: "luxury",
  },
  {
    title: "Himalayan Stone Cottage with Pine Forest",
    description: "Nestled quietly above old Manali overlooking snow-capped Pir Panjal peaks. Wooden interiors, artisan wood stove, balcony stargazing, and Apple orchards.",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
    price: 5200,
    location: "Manali, Himachal Pradesh",
    country: "India",
    category: "mountains",
  },
  {
    title: "Historic Medieval Castle in Scottish Highlands",
    description: "Live like nobility in a restored 16th-century stone fortress. Sprawling 40-acre estate, grand stone hearths, spiral turrets, and private loch views.",
    image: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80",
    price: 45000,
    location: "Inverness",
    country: "United Kingdom",
    category: "castles",
  },
  {
    title: "Luxury Infinity Pool Villa in Amalfi",
    description: "Commanding breathtaking Mediterranean views from high above Positano. Multi-tiered citrus gardens, private cliffside pool, and sunlit terracotta terrace.",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    price: 38000,
    location: "Positano, Amalfi Coast",
    country: "Italy",
    category: "pools",
  },
  {
    title: "Traditional Machiya Townhouse in Kyoto",
    description: "Step back into Edo-era Kyoto within Gion historical district. Tatami straw mats, sliding shoji screens, serene zen rock garden, and cypress wood soaking bath.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    price: 18500,
    location: "Kyoto",
    country: "Japan",
    category: "iconic-cities",
  },
  {
    title: "Glass Igloo Under the Northern Lights",
    description: "Sleep underneath a dome of heated glass with front-row seats to the Aurora Borealis. Reindeer safari nearby, private sauna, and snowshoe trails.",
    image: "https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80",
    price: 27500,
    location: "Rovaniemi, Lapland",
    country: "Finland",
    category: "arctic",
  },
  {
    title: "Rustic Vineyard Farmhouse in Tuscany",
    description: "Surrounded by rolling olive groves and Chianti vineyards. Brick arches, handcrafted wooden furniture, wine cellar tastings, and wood-fired pizza oven.",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80",
    price: 16000,
    location: "Siena, Tuscany",
    country: "Italy",
    category: "farms",
  },
  {
    title: "Safari Eco-Glamping Camp in Serengeti",
    description: "Intimate canvas luxury safari tents in the heart of wildlife migration routes. Solar powered, open-fire dining under stars, and daily sunrise game drives.",
    image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1200&q=80",
    price: 24000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "camping",
  },
  {
    title: "Penthouse Loft Overlooking Manhattan Skyline",
    description: "Soaring 14-foot ceilings, floor-to-ceiling windows, private landscaped rooftop terrace, chef kitchen, and panoramic views of the Empire State Building.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    price: 36000,
    location: "SoHo, New York City",
    country: "United States",
    category: "iconic-cities",
  },
  {
    title: "Heritage Haveli Suite in Jaipur Pink City",
    description: "Intricately carved sandstone arches, royal courtyard fountains, fresco wall paintings, rooftop stargazing over Nahargarh Fort, and warm Rajasthani hospitality.",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    price: 7800,
    location: "Jaipur, Rajasthan",
    country: "India",
    category: "rooms",
  },
  {
    title: "Cliffside Overwater Bungalow in Bora Bora",
    description: "Turquoise lagoon beneath your glass floor panel. Private sundeck, direct ocean ladder access, outdoor daybed, and breakfast delivered by outrigger canoe.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    price: 54000,
    location: "Bora Bora",
    country: "French Polynesia",
    category: "luxury",
  },
  {
    title: "Lakeview Swiss Chalet in Zermatt",
    description: "Unparalleled views of the majestic Matterhorn. Expansive sunny balcony, modern gourmet kitchen, heated oak floors, and outdoor geothermal hot tub.",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80",
    price: 29000,
    location: "Zermatt, Valais",
    country: "Switzerland",
    category: "mountains",
  },
  {
    title: "Tranquil Backwater Houseboat in Kerala",
    description: "Glide gently through palm-fringed lagoons and paddy fields. Traditional thatched teakwood barge with air-conditioned staterooms and personal onboard chef.",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    price: 8800,
    location: "Alleppey, Kerala",
    country: "India",
    category: "boats",
  },
];

module.exports = { data: sampleListings };
